In [1]:
import pandas as pd

In [2]:
bangalore = pd.read_csv('Bookings.csv')

In [3]:
ncr = pd.read_csv('ncr_ride_bookings.csv')

In [4]:
print("Bangalore shape:", bangalore.shape)
print("NCR shape:", ncr.shape)

Bangalore shape: (103024, 21)
NCR shape: (150000, 21)

In [5]:
bangalore.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,#NAME?,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
3,2024-07-22 3:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,NaN,384,NaN,0,NaN,NaN,#NAME?,NaN
4,2024-07-02 9:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN

In [6]:
ncr.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [7]:
print("Bangalore columns:\n", bangalore.columns)
print("\nNCR columns:\n", ncr.columns)

Bangalore columns:
 Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehicle Images', 'Unnamed: 20'],
      dtype='object')

NCR columns:
 Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='object')

In [8]:
bangalore["Date"] = pd.to_datetime(bangalore["Date"], errors='coerce')
bangalore["Time"] = bangalore["Date"].dt.time
bangalore["Date"] = bangalore["Date"].dt.date

In [9]:
ncr["Date"] = pd.to_datetime(ncr["Date"], errors='coerce')

In [10]:
bangalore.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Unnamed: 20
0,2024-07-26,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,#NAME?,NaN
1,2024-07-25,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,NaN,No,NaN,158,Cash,13,4.1,4.0,#NAME?,NaN
2,2024-07-30,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,NaN,No,NaN,386,UPI,40,4.2,4.8,#NAME?,NaN
3,2024-07-22,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,NaN,384,NaN,0,NaN,NaN,#NAME?,NaN
4,2024-07-02,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,NaN,No,NaN,822,Credit Card,45,4.0,3.0,#NAME?,NaN

In [11]:
ncr.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [13]:
bangalore["Booking_ID"] = bangalore["Booking_ID"].astype(str)
ncr["Booking ID"] = ncr["Booking ID"].astype(str)

In [14]:
bangalore["Booking_Status"] = bangalore["Booking_Status"].replace({
    "Success": "Completed",
    "Driver Not Found": "No Driver Found",
    "Canceled by Customer": "Cancelled by Customer",
    "Canceled by Driver": "Cancelled by Driver"
})

In [15]:
ncr["Booking Status"] = ncr["Booking Status"].replace({
    "Completed": "Completed",
    "No Driver Found": "No Driver Found",
    "Cancelled by Customer": "Cancelled by Customer",
    "Cancelled by Driver": "Cancelled by Driver",
    "Incomplete": "Incomplete"
})

In [16]:
bangalore["Cancellation_Reason_Customer"] = bangalore["Canceled_Rides_by_Customer"]
bangalore["Cancellation_Reason_Driver"] = bangalore["Canceled_Rides_by_Driver"]

bangalore["Cancelled_By_Customer"] = bangalore["Canceled_Rides_by_Customer"].notnull().astype(int)
bangalore["Cancelled_By_Driver"] = bangalore["Canceled_Rides_by_Driver"].notnull().astype(int)

In [17]:
bangalore["Incomplete_Rides"] = bangalore["Incomplete_Rides"].replace({
    "yes": 1,
    "no": 0
})

# Handle nulls
bangalore["Incomplete_Rides"] = bangalore["Incomplete_Rides"].fillna(0)

In [19]:
ncr["Incomplete Rides"] = ncr["Incomplete Rides"].fillna(0)

In [21]:
payment_map = {
    "Cash": "Cash",
    "UPI": "UPI",
    "Credit Card": "Card",
    "Debit Card": "Card",
    "Uber Wallet": "Wallet"
}

# Apply mapping
bangalore["Payment_Method"] = bangalore["Payment_Method"].map(payment_map)
ncr["Payment Method"] = ncr["Payment Method"].map(payment_map)

# Handle null values
bangalore["Payment_Method"] = bangalore["Payment_Method"].fillna("Unknown")
ncr["Payment Method"] = ncr["Payment Method"].fillna("Unknown")

In [22]:
bangalore = bangalore.drop(columns=["Vehicle Images"], errors='ignore')

In [23]:
print("Bangalore columns:\n", bangalore.columns)
print("\nNCR columns:\n", ncr.columns)

Bangalore columns:
 Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Unnamed: 20', 'Cancellation_Reason_Customer',
       'Cancellation_Reason_Driver', 'Cancelled_By_Customer',
       'Cancelled_By_Driver'],
      dtype='object')

NCR columns:
 Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='object')

In [24]:
ncr = ncr.rename(columns={
    "Booking ID": "Booking_ID",
    "Booking Status": "Booking_Status",
    "Customer ID": "Customer_ID",
    "Vehicle Type": "Vehicle_Type",
    "Pickup Location": "Pickup_Location",
    "Drop Location": "Drop_Location",
    "Avg VTAT": "VTAT",
    "Avg CTAT": "CTAT",
    "Cancelled Rides by Customer": "Cancelled_By_Customer",
    "Cancelled Rides by Driver": "Cancelled_By_Driver",
    "Reason for cancelling by Customer": "Cancellation_Reason_Customer",
    "Driver Cancellation Reason": "Cancellation_Reason_Driver",
    "Incomplete Rides": "Incomplete_Rides",
    "Incomplete Rides Reason": "Incomplete_Reason",
    "Booking Value": "Booking_Value",
    "Ride Distance": "Ride_Distance",
    "Driver Ratings": "Driver_Rating",
    "Customer Rating": "Customer_Rating",
    "Payment Method": "Payment_Method"
})

In [25]:
bangalore = bangalore.drop(columns=["Unnamed: 20"], errors='ignore')

In [26]:
print("Bangalore columns:\n", bangalore.columns)
print("\nNCR columns:\n", ncr.columns)

Bangalore columns:
 Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Cancellation_Reason_Customer', 'Cancellation_Reason_Driver',
       'Cancelled_By_Customer', 'Cancelled_By_Driver'],
      dtype='object')

NCR columns:
 Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'VTAT', 'CTAT',
       'Cancelled_By_Customer', 'Cancellation_Reason_Customer',
       'Cancelled_By_Driver', 'Cancellation_Reason_Driver', 'Incomplete_Rides',
       'Incomplete_Reason', 'Booking_Value', 'Ride_Distance', 'Driver_Rating',
       'Customer_Rating', 'Payment_Method'],
      dtype='object')

In [27]:
bangalore = bangalore.rename(columns={
    "V_TAT": "VTAT",
    "C_TAT": "CTAT",
    "Driver_Ratings": "Driver_Rating",
    "Incomplete_Rides_Reason": "Incomplete_Reason"
})

In [28]:
bangalore = bangalore[[
    "Date", "Time", "Booking_ID", "Booking_Status", "Customer_ID",
    "Vehicle_Type", "Pickup_Location", "Drop_Location",
    "VTAT", "CTAT",
    "Cancellation_Reason_Customer", "Cancellation_Reason_Driver",
    "Incomplete_Rides", "Incomplete_Reason",
    "Booking_Value", "Payment_Method", "Ride_Distance",
    "Driver_Rating", "Customer_Rating"
]]

In [29]:
bangalore["Cancelled_By_Customer"] = bangalore["Cancellation_Reason_Customer"].notnull().astype(int)
bangalore["Cancelled_By_Driver"] = bangalore["Cancellation_Reason_Driver"].notnull().astype(int)

In [30]:
bangalore = bangalore[[
    "Date", "Time", "Booking_ID", "Booking_Status", "Customer_ID",
    "Vehicle_Type", "Pickup_Location", "Drop_Location",
    "VTAT", "CTAT",
    "Cancelled_By_Customer", "Cancelled_By_Driver",
    "Cancellation_Reason_Customer", "Cancellation_Reason_Driver",
    "Incomplete_Rides", "Incomplete_Reason",
    "Booking_Value", "Payment_Method", "Ride_Distance",
    "Driver_Rating", "Customer_Rating"
]]

In [31]:
print("Bangalore columns:\n", bangalore.columns)
print("\nNCR columns:\n", ncr.columns)

Bangalore columns:
 Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'VTAT', 'CTAT',
       'Cancelled_By_Customer', 'Cancelled_By_Driver',
       'Cancellation_Reason_Customer', 'Cancellation_Reason_Driver',
       'Incomplete_Rides', 'Incomplete_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Rating', 'Customer_Rating'],
      dtype='object')

NCR columns:
 Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'VTAT', 'CTAT',
       'Cancelled_By_Customer', 'Cancellation_Reason_Customer',
       'Cancelled_By_Driver', 'Cancellation_Reason_Driver', 'Incomplete_Rides',
       'Incomplete_Reason', 'Booking_Value', 'Ride_Distance', 'Driver_Rating',
       'Customer_Rating', 'Payment_Method'],
      dtype='object')

In [32]:
bangalore.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Cancelled_By_Driver,Cancellation_Reason_Customer,Cancellation_Reason_Driver,Incomplete_Rides,Incomplete_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Rating,Customer_Rating
0,2024-07-26,14:00:00,CNR7153255142,Cancelled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,1,NaN,Personal & Car related issue,0,NaN,444,Unknown,0,NaN,NaN
1,2024-07-25,22:20:00,CNR2940424040,Completed,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0
2,2024-07-30,19:59:00,CNR2982357879,Completed,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8
3,2024-07-22,03:15:00,CNR2395710036,Cancelled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,0,Driver is not moving towards pickup location,NaN,0,NaN,384,Unknown,0,NaN,NaN
4,2024-07-02,09:02:00,CNR1797421769,Completed,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,0,NaN,NaN,No,NaN,822,Unknown,45,4.0,3.0

In [33]:
ncr.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Cancellation_Reason_Customer,Cancelled_By_Driver,Cancellation_Reason_Driver,Incomplete_Rides,Incomplete_Reason,Booking_Value,Ride_Distance,Driver_Rating,Customer_Rating,Payment_Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,Unknown
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,0.0,NaN,627.0,13.58,4.9,4.9,Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,0.0,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,0.0,NaN,737.0,48.21,4.1,4.3,UPI

In [34]:
cols = [
    'Cancelled_By_Customer',
    'Cancelled_By_Driver',
    'Cancellation_Reason_Customer',
    'Cancellation_Reason_Driver'
]

for col in cols:
    print(f"\n🔹 {col} (Bangalore):")
    print(bangalore[col].dropna().unique())

🔹 Cancelled_By_Customer (Bangalore):
[0 1]

🔹 Cancelled_By_Driver (Bangalore):
[1 0]

🔹 Cancellation_Reason_Customer (Bangalore):
['Driver is not moving towards pickup location' 'Driver asked to cancel'
 'AC is Not working' 'Change of plans' 'Wrong Address']

🔹 Cancellation_Reason_Driver (Bangalore):
['Personal & Car related issue' 'Customer was coughing/sick'
 'Customer related issue' 'More than permitted people in there']

In [35]:
for col in cols:
    print(f"\n🔹 {col} (NCR):")
    print(ncr[col].dropna().unique())

🔹 Cancelled_By_Customer (NCR):
[1.]

🔹 Cancelled_By_Driver (NCR):
[1.]

🔹 Cancellation_Reason_Customer (NCR):
['Driver is not moving towards pickup location' 'Driver asked to cancel'
 'AC is not working' 'Change of plans' 'Wrong Address']

🔹 Cancellation_Reason_Driver (NCR):
['Personal & Car related issues' 'Customer related issue'
 'More than permitted people in there' 'The customer was coughing/sick']

In [36]:
ncr["Cancelled_By_Customer"] = ncr["Cancelled_By_Customer"].fillna(0)
ncr["Cancelled_By_Driver"] = ncr["Cancelled_By_Driver"].fillna(0)

In [37]:
ncr["Cancelled_By_Customer"] = (ncr["Cancelled_By_Customer"] > 0).astype(int)
ncr["Cancelled_By_Driver"] = (ncr["Cancelled_By_Driver"] > 0).astype(int)

In [38]:
ncr["Cancelled_By_Customer"] = ncr["Cancelled_By_Customer"].astype(int)
ncr["Cancelled_By_Driver"] = ncr["Cancelled_By_Driver"].astype(int)

In [39]:
print(ncr["Cancelled_By_Customer"].unique())
print(ncr["Cancelled_By_Driver"].unique())

[0 1]
[0 1]

In [40]:
print("Bangalore - Incomplete_Rides:")
print(bangalore["Incomplete_Rides"].unique())

print("\nBangalore - Incomplete_Reason:")
print(bangalore["Incomplete_Reason"].dropna().unique())

Bangalore - Incomplete_Rides:
[0 'No' 'Yes']

Bangalore - Incomplete_Reason:
['Customer Demand' 'Vehicle Breakdown' 'Other Issue']

In [41]:
print("NCR - Incomplete_Rides:")
print(ncr["Incomplete_Rides"].unique())

print("\nNCR - Incomplete_Reason:")
print(ncr["Incomplete_Reason"].dropna().unique())

NCR - Incomplete_Rides:
[0. 1.]

NCR - Incomplete_Reason:
['Vehicle Breakdown' 'Other Issue' 'Customer Demand']

In [42]:
print("\nBangalore Incomplete_Rides:")
print(bangalore["Incomplete_Rides"].value_counts(dropna=False))

print("\nNCR Incomplete_Rides:")
print(ncr["Incomplete_Rides"].value_counts(dropna=False))

Bangalore Incomplete_Rides:
Incomplete_Rides
No     60041
0      39057
Yes     3926
Name: count, dtype: int64

NCR Incomplete_Rides:
Incomplete_Rides
0.0    141000
1.0      9000
Name: count, dtype: int64

In [43]:
print("\nBangalore Incomplete_Reason:")
print(bangalore["Incomplete_Reason"].value_counts(dropna=False))

print("\nNCR Incomplete_Reason:")
print(ncr["Incomplete_Reason"].value_counts(dropna=False))

Bangalore Incomplete_Reason:
Incomplete_Reason
NaN                  99098
Customer Demand       1601
Vehicle Breakdown     1591
Other Issue            734
Name: count, dtype: int64

NCR Incomplete_Reason:
Incomplete_Reason
NaN                  141000
Customer Demand        3040
Vehicle Breakdown      3012
Other Issue            2948
Name: count, dtype: int64

In [44]:
bangalore["Incomplete_Rides"] = bangalore["Incomplete_Rides"].replace({
    "Yes": 1,
    "No": 0
})

# Convert everything to numeric
bangalore["Incomplete_Rides"] = pd.to_numeric(bangalore["Incomplete_Rides"], errors='coerce').fillna(0).astype(int)

/tmp/ipykernel_1202/2247118743.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bangalore["Incomplete_Rides"] = bangalore["Incomplete_Rides"].replace({

In [45]:
bangalore["Incomplete_Rides"] = bangalore["Incomplete_Rides"].map({
    "Yes": 1,
    "No": 0,
    0: 0,
    1: 1
})

bangalore["Incomplete_Rides"] = bangalore["Incomplete_Rides"].fillna(0).astype(int)

In [46]:
ncr["Incomplete_Rides"] = (
    pd.to_numeric(ncr["Incomplete_Rides"], errors='coerce')
    .fillna(0)
    .astype(int)
)

In [47]:
print(bangalore["Incomplete_Rides"].unique())
print(bangalore["Incomplete_Rides"].dtype)

[0 1]
int64

In [48]:
print(ncr["Incomplete_Rides"].unique())
print(ncr["Incomplete_Rides"].dtype)

[0 1]
int64

In [50]:
print("Bangalore Sample:")
display(bangalore.sample(50))

print("\nNCR Sample:")
display(ncr.sample(50))

Bangalore Sample:

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Cancelled_By_Driver,Cancellation_Reason_Customer,Cancellation_Reason_Driver,Incomplete_Rides,Incomplete_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Rating,Customer_Rating
49013,2024-07-09,06:14:00,CNR5589723863,Completed,CID325601,Auto,Tumkur Road,Cox Town,210.0,40.0,...,0,NaN,NaN,0,NaN,831,UPI,8,3.6,3.1
39258,2024-07-30,18:08:00,CNR7697753844,No Driver Found,CID210576,Auto,Sarjapur Road,Chamarajpet,NaN,NaN,...,0,NaN,NaN,0,NaN,775,Unknown,0,NaN,NaN
2473,2024-07-02,21:56:00,CNR2753808775,Completed,CID159145,Prime Sedan,Basavanagudi,JP Nagar,84.0,60.0,...,0,NaN,NaN,0,NaN,364,UPI,45,3.9,4.7
90486,2024-07-03,23:35:00,CNR1916358256,Completed,CID736051,Prime Plus,Chickpet,Chamarajpet,84.0,110.0,...,0,NaN,NaN,0,NaN,274,UPI,37,4.5,4.3
19122,2024-07-28,11:33:00,CNR3488004005,Completed,CID149940,Mini,Koramangala,Bellandur,56.0,125.0,...,0,NaN,NaN,0,NaN,250,Cash,29,4.6,4.6
72463,2024-07-21,01:59:00,CNR5891051121,Completed,CID970688,Mini,Shantinagar,Padmanabhanagar,63.0,60.0,...,0,NaN,NaN,0,NaN,468,Cash,4,4.9,4.8
86341,2024-07-05,20:18:00,CNR5397077326,Completed,CID359226,Prime SUV,Hosur Road,Frazer Town,91.0,145.0,...,0,NaN,NaN,0,NaN,228,UPI,9,3.7,3.1
46784,2024-07-26,11:20:00,CNR8213829946,Completed,CID533064,eBike,KR Puram,Ramamurthy Nagar,287.0,50.0,...,0,NaN,NaN,0,NaN,342,Cash,30,4.3,4.3
51574,2024-07-27,16:39:00,CNR6819256185,Completed,CID662811,Prime Sedan,Frazer Town,Koramangala,287.0,30.0,...,0,NaN,NaN,0,NaN,340,UPI,42,4.5,3.4
42689,2024-07-09,02:30:00,CNR9141393057,Completed,CID149191,Prime Plus,Kammanahalli,Vijayanagar,273.0,50.0,...,0,NaN,NaN,0,NaN,419,UPI,3,3.2,4.0
4455,2024-07-20,22:13:00,CNR7464321848,No Driver Found,CID113513,Mini,JP Nagar,HSR Layout,NaN,NaN,...,0,NaN,NaN,0,NaN,250,Unknown,0,NaN,NaN
94257,2024-07-19,23:48:00,CNR2072017730,Completed,CID207452,eBike,Yelahanka,Majestic,217.0,70.0,...,0,NaN,NaN,0,NaN,160,Cash,49,3.5,3.9
3979,2024-07-25,20:36:00,CNR1425173377,Completed,CID183695,Mini,Shantinagar,Rajarajeshwari Nagar,280.0,75.0,...,0,NaN,NaN,0,NaN,104,UPI,19,4.4,3.6
39916,2024-07-15,07:43:00,CNR6988652860,No Driver Found,CID300210,Mini,Yeshwanthpur,Chamarajpet,NaN,NaN,...,0,NaN,NaN,0,NaN,258,Unknown,0,NaN,NaN
40729,2024-07-26,19:08:00,CNR5759756430,Completed,CID553363,Mini,Rajarajeshwari Nagar,Nagarbhavi,91.0,115.0,...,0,NaN,NaN,0,NaN,291,Unknown,46,3.6,4.4
37763,2024-07-03,00:08:00,CNR6796111831,Completed,CID458254,eBike,Tumkur Road,Ramamurthy Nagar,294.0,55.0,...,0,NaN,NaN,0,NaN,461,Cash,8,4.7,4.3
69686,2024-07-14,07:51:00,CNR8713299764,Cancelled by Driver,CID233764,Prime Sedan,Tumkur Road,KR Puram,NaN,NaN,...,1,NaN,Customer related issue,0,NaN,803,Unknown,0,NaN,NaN
26504,2024-07-02,11:21:00,CNR6640075073,Completed,CID337014,Prime SUV,Hulimavu,Mysore Road,126.0,55.0,...,0,NaN,NaN,0,NaN,331,Cash,33,4.9,3.6
87751,2024-07-03,20:13:00,CNR4774024571,Completed,CID528494,Mini,Electronic City,Varthur,189.0,105.0,...,0,NaN,NaN,0,NaN,613,Cash,12,4.0,4.0
80286,2024-07-02,09:25:00,CNR6385788537,Completed,CID685800,eBike,Shantinagar,Hulimavu,287.0,125.0,...,0,NaN,NaN,0,NaN,825,UPI,24,4.2,3.5
11724,2024-07-30,11:38:00,CNR8224768638,Completed,CID761513,Mini,Basavanagudi,Basavanagudi,203.0,85.0,...,0,NaN,NaN,0,NaN,2647,Cash,4,4.8,3.0
14043,2024-07-14,04:01:00,CNR2729322716,Completed,CID179510,eBike,Yeshwanthpur,Kengeri,259.0,135.0,...,0,NaN,NaN,0,NaN,171,UPI,37,4.8,3.9
25185,2024-07-11,23:43:00,CNR7534716098,Completed,CID672492,Prime SUV,Richmond Town,Kammanahalli,196.0,125.0,...,0,NaN,NaN,0,NaN,357,UPI,8,4.3,3.2
33461,2024-07-23,23:42:00,CNR7002413922,Completed,CID191627,Prime Sedan,Electronic City,MG Road,91.0,65.0,...,0,NaN,NaN,0,NaN,119,Cash,47,3.9,3.7
75581,2024-07-19,21:02:00,CNR6197643041,Completed,CID140573,eBike,Shivajinagar,Indiranagar,308.0,75.0,...,0,NaN,NaN,1,Other Issue,362,Cash,16,3.2,3.4
71379,2024-07-09,02:09:00,CNR7342009408,Completed,CID427773,Prime Sedan,Ulsoor,Chamarajpet,259.0,115.0,...,0,NaN,NaN,0,NaN,682,Cash,24,3.3,4.3
81812,2024-07-23,22:17:00,CNR5419103175,Cancelled by Driver,CID111301,eBike,Richmond Town,Mysore Road,NaN,NaN,...,1,NaN,Personal & Car related issue,0,NaN,232,Unknown,0,NaN,NaN
94039,2024-07-17,21:51:00,CNR8794046680,Completed,CID250501,Bike,Bellandur,Frazer Town,77.0,90.0,...,0,NaN,NaN,0,NaN,440,Cash,5,4.6,4.0
18208,2024-07-16,01:52:00,CNR4489810677,Cancelled by Driver,CID933715,Mini,Bellandur,Marathahalli,NaN,NaN,...,1,NaN,Personal & Car related issue,0,NaN,693,Unknown,0,NaN,NaN
56430,2024-07-26,02:05:00,CNR8147340878,Completed,CID970031,Mini,Whitefield,JP Nagar,42.0,75.0,...,0,NaN,NaN,0,NaN,835,Cash,32,4.5,3.8
94608,2024-07-02,16:37:00,CNR6427347468,Completed,CID944307,Prime Plus,Chamarajpet,Kengeri,56.0,55.0,...,0,NaN,NaN,0,NaN,612,Cash,5,4.7,3.3
30511,2024-07-08,14:24:00,CNR4784065754,Cancelled by Driver,CID634513,Auto,Devanahalli,Sarjapur Road,NaN,NaN,...,1,NaN,More than permitted people in there,0,NaN,424,Unknown,0,NaN,NaN
6638,2024-07-04,10:49:00,CNR6774718977,Cancelled by Driver,CID152967,eBike,Langford Town,Chamarajpet,NaN,NaN,...,1,NaN,Customer was coughing/sick,0,NaN,486,Unknown,0,NaN,NaN
43918,2024-07-01,09:13:00,CNR8811668966,Completed,CID141670,Prime Plus,Indiranagar,KR Puram,147.0,125.0,...,0,NaN,NaN,0,NaN,335,UPI,10,4.7,4.7
44228,2024-07-19,14:52:00,CNR4011342198,No Driver Found,CID326596,Prime Plus,Kengeri,Ramamurthy Nagar,NaN,NaN,...,0,NaN,NaN,0,NaN,368,Unknown,0,NaN,NaN
7656,2024-07-14,08:16:00,CNR3185878759,Completed,CID654692,Mini,Shantinagar,Frazer Town,98.0,70.0,...,0,NaN,NaN,0,NaN,550,Cash,2,4.6,3.8
14738,2024-07-30,06:17:00,CNR1518807140,Completed,CID502892,Mini,Yelahanka,Kadugodi,154.0,60.0,...,0,NaN,NaN,0,NaN,928,Cash,23,4.0,3.3
38301,2024-07-29,10:49:00,CNR6838218811,Completed,CID123593,Prime Plus,Koramangala,Hennur,203.0,75.0,...,0,NaN,NaN,1,Vehicle Breakdown,642,Cash,46,4.4,5.0
5089,2024-07-21,04:15:00,CNR9555644377,Completed,CID776410,Mini,Hennur,Koramangala,259.0,125.0,...,0,NaN,NaN,0,NaN,390,UPI,11,3.1,4.9
6570,2024-07-17,19:53:00,CNR6942641820,Completed,CID852504,eBike,Yelahanka,Frazer Town,308.0,70.0,...,0,NaN,NaN,0,NaN,485,Cash,27,3.8,4.5
68170,2024-07-15,16:46:00,CNR3355869805,Completed,CID339184,Mini,Bellandur,Shantinagar,189.0,45.0,...,0,NaN,NaN,0,NaN,642,Cash,26,4.7,4.6
99729,2024-07-24,00:14:00,CNR8532970914,Cancelled by Driver,CID768010,eBike,Mysore Road,Kengeri,NaN,NaN,...,1,NaN,Customer related issue,0,NaN,214,Unknown,0,NaN,NaN
10973,2024-07-10,21:48:00,CNR8665230105,Cancelled by Driver,CID906991,Auto,Cox Town,Chickpet,NaN,NaN,...,1,NaN,Customer was coughing/sick,0,NaN,520,Unknown,0,NaN,NaN
18372,2024-07-02,13:52:00,CNR7330232955,Cancelled by Customer,CID471131,Prime Sedan,Kengeri,Banashankari,NaN,NaN,...,0,AC is Not working,NaN,0,NaN,888,Unknown,0,NaN,NaN
77380,2024-07-10,06:44:00,CNR5092182498,Cancelled by Driver,CID800481,Bike,BTM Layout,Kengeri,NaN,NaN,...,1,NaN,Personal & Car related issue,0,NaN,299,Unknown,0,NaN,NaN
85493,2024-07-30,22:06:00,CNR5916315645,Completed,CID928124,Auto,Bannerghatta Road,Bellandur,112.0,130.0,...,0,NaN,NaN,0,NaN,899,UPI,18,3.2,4.7
100721,2024-07-31,13:43:00,CNR3092643086,Completed,CID209368,Prime SUV,Koramangala,Malleshwaram,112.0,130.0,...,0,NaN,NaN,0,NaN,158,UPI,24,3.9,4.9
32161,2024-07-27,22:49:00,CNR8210447357,Completed,CID118718,Prime Sedan,Sahakar Nagar,Nagarbhavi,294.0,75.0,...,0,NaN,NaN,0,NaN,138,Cash,15,3.2,4.1
68600,2024-07-06,11:42:00,CNR1959897924,Completed,CID527874,Prime Sedan,Rajarajeshwari Nagar,Banashankari,168.0,85.0,...,0,NaN,NaN,0,NaN,689,UPI,47,3.1,3.9
100612,2024-07-31,23:16:00,CNR3697533600,Completed,CID882123,Bike,Devanahalli,Yeshwanthpur,294.0,45.0,...,0,NaN,NaN,0,NaN,424,Cash,14,4.4,4.2

NCR Sample:

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Cancellation_Reason_Customer,Cancelled_By_Driver,Cancellation_Reason_Driver,Incomplete_Rides,Incomplete_Reason,Booking_Value,Ride_Distance,Driver_Rating,Customer_Rating,Payment_Method
57952,2024-12-08,04:48:50,"""CNR8500750""",Cancelled by Customer,"""CID4389470""",Go Mini,Sadar Bazar Gurgaon,Aya Nagar,5.1,NaN,...,Wrong Address,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
117749,2024-12-26,17:27:30,"""CNR4888543""",Completed,"""CID5044844""",Go Mini,Akshardham,Karol Bagh,9.1,25.5,...,NaN,0,NaN,0,NaN,683.0,23.59,4.9,4.3,Cash
77563,2024-10-21,17:12:29,"""CNR7331569""",Cancelled by Customer,"""CID5904822""",Go Mini,Azadpur,Tis Hazari,16.9,NaN,...,Change of plans,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
71138,2024-03-16,18:51:43,"""CNR9185833""",Completed,"""CID9291686""",Go Mini,Laxmi Nagar,Sarai Kale Khan,8.2,16.0,...,NaN,0,NaN,0,NaN,1184.0,16.42,4.6,3.6,Wallet
59751,2024-12-21,19:51:36,"""CNR5211182""",Completed,"""CID4909023""",Uber XL,Patel Chowk,Vasant Kunj,14.2,16.0,...,NaN,0,NaN,0,NaN,244.0,15.02,4.3,5.0,Card
20531,2024-08-18,12:47:57,"""CNR4222333""",Incomplete,"""CID5744538""",Go Sedan,IFFCO Chowk,DLF Phase 3,5.6,18.7,...,NaN,0,NaN,1,Vehicle Breakdown,1229.0,17.20,NaN,NaN,UPI
99171,2024-02-05,08:06:40,"""CNR2095862""",Completed,"""CID7756554""",Go Sedan,Palam Vihar,Kanhaiya Nagar,7.7,21.8,...,NaN,0,NaN,0,NaN,338.0,10.83,4.3,4.1,Cash
52300,2024-11-06,22:56:25,"""CNR9723471""",Cancelled by Driver,"""CID9650307""",Go Mini,Akshardham,Sushant Lok,7.9,NaN,...,NaN,1,Customer related issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
118242,2024-10-13,07:49:39,"""CNR6265041""",Completed,"""CID5596232""",eBike,Shastri Nagar,Janakpuri,6.4,29.9,...,NaN,0,NaN,0,NaN,1181.0,46.34,4.5,4.7,Cash
128161,2024-11-28,11:06:57,"""CNR9445500""",Cancelled by Driver,"""CID2305070""",Bike,Hauz Khas,Pataudi Chowk,3.5,NaN,...,NaN,1,Personal & Car related issues,0,NaN,NaN,NaN,NaN,NaN,Unknown
40851,2024-05-03,19:19:15,"""CNR7317955""",Completed,"""CID5793075""",Auto,Panchsheel Park,Gwal Pahari,8.4,23.9,...,NaN,0,NaN,0,NaN,72.0,10.40,3.8,4.7,Card
124001,2024-10-28,21:17:55,"""CNR6318135""",Completed,"""CID8441701""",Bike,Kirti Nagar,Shastri Nagar,13.1,41.7,...,NaN,0,NaN,0,NaN,719.0,6.83,4.4,4.4,UPI
116765,2024-04-26,21:58:02,"""CNR6474592""",Completed,"""CID1457629""",Auto,Panchsheel Park,Ambience Mall,2.3,25.1,...,NaN,0,NaN,0,NaN,218.0,39.11,4.9,4.6,Card
100556,2024-06-15,11:07:22,"""CNR8372988""",Completed,"""CID7466126""",Auto,Lajpat Nagar,Ashok Vihar,9.1,15.3,...,NaN,0,NaN,0,NaN,82.0,38.98,4.2,4.3,UPI
126379,2024-04-27,13:45:43,"""CNR9272673""",Completed,"""CID8251232""",Auto,Okhla,Udyog Vihar,6.3,18.5,...,NaN,0,NaN,0,NaN,366.0,27.11,4.4,4.9,Wallet
26861,2024-04-09,21:41:43,"""CNR7227535""",Completed,"""CID6422816""",eBike,Moolchand,Manesar,6.6,34.4,...,NaN,0,NaN,0,NaN,203.0,45.50,4.9,4.3,UPI
129647,2024-12-09,16:54:10,"""CNR8388076""",Completed,"""CID8169008""",Go Mini,Shastri Park,Rohini,3.8,21.6,...,NaN,0,NaN,0,NaN,979.0,2.13,4.6,4.2,Cash
18720,2024-11-09,21:48:46,"""CNR2226718""",Completed,"""CID4691524""",Go Mini,Green Park,Janakpuri,14.8,19.6,...,NaN,0,NaN,0,NaN,693.0,15.78,4.0,4.8,UPI
11162,2024-03-19,16:03:20,"""CNR1433354""",Completed,"""CID1818755""",Bike,Ambience Mall,Chandni Chowk,7.7,23.2,...,NaN,0,NaN,0,NaN,787.0,48.80,4.2,3.4,Card
45339,2024-06-21,10:32:19,"""CNR6087730""",Cancelled by Customer,"""CID8869880""",Premier Sedan,Sohna Road,Sushant Lok,11.7,NaN,...,AC is not working,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
113854,2024-02-29,07:00:35,"""CNR9514047""",Completed,"""CID8223589""",Go Mini,Shivaji Park,Anand Vihar ISBT,2.7,18.0,...,NaN,0,NaN,0,NaN,159.0,2.69,4.7,4.6,UPI
142016,2024-02-03,17:05:50,"""CNR5917292""",Completed,"""CID5621866""",Bike,Kanhaiya Nagar,Ashok Park Main,9.2,23.2,...,NaN,0,NaN,0,NaN,441.0,41.76,4.4,4.4,UPI
80630,2024-06-24,18:49:32,"""CNR9853991""",Cancelled by Driver,"""CID7957055""",Go Mini,South Extension,Govindpuri,7.7,NaN,...,NaN,1,More than permitted people in there,0,NaN,NaN,NaN,NaN,NaN,Unknown
14782,2024-03-02,18:33:54,"""CNR7579339""",Completed,"""CID1529994""",Go Mini,Bhiwadi,Sushant Lok,2.6,38.5,...,NaN,0,NaN,0,NaN,231.0,18.85,4.7,3.7,Cash
5661,2024-10-14,19:10:34,"""CNR9201886""",Completed,"""CID3750157""",Bike,Moti Nagar,Maidan Garhi,3.1,31.9,...,NaN,0,NaN,0,NaN,106.0,4.61,4.3,4.3,UPI
111823,2024-10-10,20:30:34,"""CNR7753489""",Completed,"""CID8963355""",Go Sedan,Subhash Chowk,Ghaziabad,11.3,20.0,...,NaN,0,NaN,0,NaN,720.0,46.63,5.0,4.6,Wallet
1893,2024-11-02,10:45:25,"""CNR8512595""",Completed,"""CID8017027""",Auto,Ashok Vihar,Mehrauli,14.6,29.6,...,NaN,0,NaN,0,NaN,294.0,44.22,3.6,5.0,Cash
8240,2024-03-23,06:39:51,"""CNR6115322""",No Driver Found,"""CID1736469""",Go Mini,Badshahpur,Dilshad Garden,NaN,NaN,...,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
133069,2024-04-12,05:34:14,"""CNR2364703""",Completed,"""CID1259924""",Go Mini,Satguru Ram Singh Marg,IMT Manesar,12.5,29.2,...,NaN,0,NaN,0,NaN,72.0,47.84,3.6,4.2,Card
53794,2024-11-26,20:47:17,"""CNR1933484""",Completed,"""CID7655543""",Go Sedan,Ashok Vihar,Madipur,5.3,42.6,...,NaN,0,NaN,0,NaN,537.0,31.58,5.0,4.6,Card
97410,2024-06-14,07:18:25,"""CNR9761135""",Cancelled by Customer,"""CID3442668""",Go Mini,Anand Vihar ISBT,ITO,16.3,NaN,...,Change of plans,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
117257,2024-02-17,20:57:13,"""CNR3396155""",Cancelled by Customer,"""CID3746254""",Auto,Govindpuri,Maidan Garhi,10.0,NaN,...,Driver is not moving towards pickup location,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
141720,2024-12-08,02:02:32,"""CNR6913493""",Completed,"""CID3054411""",Go Mini,Jama Masjid,Kherki Daula Toll,10.3,17.4,...,NaN,0,NaN,0,NaN,583.0,33.27,3.1,4.7,UPI
97968,2024-06-28,07:32:00,"""CNR1401035""",Completed,"""CID9491449""",Premier Sedan,Ashok Park Main,Mayur Vihar,5.8,40.3,...,NaN,0,NaN,0,NaN,337.0,19.89,3.8,4.3,Cash
47925,2024-02-01,17:52:28,"""CNR5680746""",Completed,"""CID2767510""",eBike,Satguru Ram Singh Marg,Mayur Vihar,11.8,34.6,...,NaN,0,NaN,0,NaN,492.0,48.72,4.2,4.6,Cash
16392,2024-12-27,18:33:44,"""CNR9046570""",Completed,"""CID9585899""",Go Mini,Jor Bagh,Udyog Vihar Phase 4,5.7,30.5,...,NaN,0,NaN,0,NaN,435.0,26.48,4.3,4.2,Cash
40068,2024-04-21,15:28:17,"""CNR9916595""",Cancelled by Driver,"""CID5810168""",Go Sedan,Mansarovar Park,Sarai Kale Khan,4.7,NaN,...,NaN,1,Customer related issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
142354,2024-09-27,23:06:25,"""CNR3311416""",Completed,"""CID8001584""",eBike,Ashok Park Main,Pataudi Chowk,4.8,40.8,...,NaN,0,NaN,0,NaN,435.0,23.10,4.6,4.9,UPI
41430,2024-01-03,10:49:29,"""CNR2692143""",Cancelled by Driver,"""CID2978442""",Go Mini,Pitampura,Noida Extension,8.0,NaN,...,NaN,1,Customer related issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
119927,2024-08-16,11:33:51,"""CNR7911447""",Cancelled by Driver,"""CID7805085""",Auto,Noida Film City,Samaypur Badli,5.6,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,Unknown
17384,2024-04-02,04:29:21,"""CNR1316256""",Cancelled by Driver,"""CID4833491""",Bike,Welcome,Uttam Nagar,4.8,NaN,...,NaN,1,The customer was coughing/sick,0,NaN,NaN,NaN,NaN,NaN,Unknown
136189,2024-02-10,18:24:13,"""CNR6956121""",Cancelled by Customer,"""CID1448013""",Premier Sedan,Bhiwadi,Ashok Vihar,16.4,NaN,...,Change of plans,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
40429,2024-08-14,17:14:54,"""CNR9885317""",Completed,"""CID1661635""",Auto,Shahdara,Uttam Nagar,13.4,36.8,...,NaN,0,NaN,0,NaN,80.0,40.38,3.7,4.5,Card
59673,2024-11-26,18:25:37,"""CNR2488734""",Completed,"""CID3983288""",eBike,Okhla,Paharganj,6.5,27.4,...,NaN,0,NaN,0,NaN,263.0,42.86,4.5,3.7,Wallet
1167,2024-02-26,15:41:04,"""CNR5659221""",Completed,"""CID7389969""",Auto,Connaught Place,Ramesh Nagar,13.1,27.8,...,NaN,0,NaN,0,NaN,408.0,4.17,3.7,4.3,UPI
56873,2024-08-14,19:57:11,"""CNR8830864""",Completed,"""CID6122373""",Go Sedan,Green Park,Pulbangash,11.3,32.3,...,NaN,0,NaN,0,NaN,457.0,36.22,3.1,3.8,UPI
127873,2024-09-20,16:50:06,"""CNR6011540""",Completed,"""CID6680930""",Go Sedan,Satguru Ram Singh Marg,Arjangarh,2.5,27.3,...,NaN,0,NaN,0,NaN,965.0,34.98,4.7,3.2,Cash
32311,2024-12-01,08:34:38,"""CNR8095764""",Completed,"""CID9867611""",Go Sedan,Rajouri Garden,Ashok Vihar,9.4,26.0,...,NaN,0,NaN,0,NaN,436.0,34.61,4.6,3.6,UPI
7949,2024-12-03,16:18:50,"""CNR4050003""",Completed,"""CID3406930""",Go Mini,Subhash Nagar,Paschim Vihar,4.1,42.8,...,NaN,0,NaN,0,NaN,318.0,34.04,4.4,3.7,Cash
109219,2024-11-10,17:38:51,"""CNR4578458""",Cancelled by Driver,"""CID2498076""",Bike,Faridabad Sector 15,Lal Quila,10.8,NaN,...,NaN,1,Customer related issue,0,NaN,NaN,NaN,NaN,NaN,Unknown

In [51]:
for col in cols:
    print(f"\n🔹 {col} (Bangalore):")
    print(bangalore[col].dropna().unique())
for col in cols:
    print(f"\n🔹 {col} (NCR):")
    print(ncr[col].dropna().unique())

🔹 Cancelled_By_Customer (Bangalore):
[0 1]

🔹 Cancelled_By_Driver (Bangalore):
[1 0]

🔹 Cancellation_Reason_Customer (Bangalore):
['Driver is not moving towards pickup location' 'Driver asked to cancel'
 'AC is Not working' 'Change of plans' 'Wrong Address']

🔹 Cancellation_Reason_Driver (Bangalore):
['Personal & Car related issue' 'Customer was coughing/sick'
 'Customer related issue' 'More than permitted people in there']

🔹 Cancelled_By_Customer (NCR):
[0 1]

🔹 Cancelled_By_Driver (NCR):
[0 1]

🔹 Cancellation_Reason_Customer (NCR):
['Driver is not moving towards pickup location' 'Driver asked to cancel'
 'AC is not working' 'Change of plans' 'Wrong Address']

🔹 Cancellation_Reason_Driver (NCR):
['Personal & Car related issues' 'Customer related issue'
 'More than permitted people in there' 'The customer was coughing/sick']

In [52]:
customer_reason_map = {
    "Driver is not moving towards pickup location": "Driver Not Moving",
    "Driver asked to cancel": "Driver Asked to Cancel",
    "AC is not working": "AC Issue",
    "Change of plans": "Change of Plans",
    "change of plans": "Change of Plans",
    "Wrong Address": "Wrong Address"
}

bangalore["Cancellation_Reason_Customer"] = bangalore["Cancellation_Reason_Customer"].map(customer_reason_map)
ncr["Cancellation_Reason_Customer"] = ncr["Cancellation_Reason_Customer"].map(customer_reason_map)

In [53]:
driver_reason_map = {
    "Personal & Car related issue": "Car Issue",
    "Personal & Car related issues": "Car Issue",
    "Customer was coughing/sick": "Customer Sick",
    "The customer was coughing/sick": "Customer Sick",
    "Customer related issue": "Customer Issue",
    "More than permitted people in there": "Over Capacity"
}

bangalore["Cancellation_Reason_Driver"] = bangalore["Cancellation_Reason_Driver"].map(driver_reason_map)
ncr["Cancellation_Reason_Driver"] = ncr["Cancellation_Reason_Driver"].map(driver_reason_map)

In [54]:
print(bangalore["Cancellation_Reason_Customer"].dropna().unique())
print(ncr["Cancellation_Reason_Customer"].dropna().unique())

print(bangalore["Cancellation_Reason_Driver"].dropna().unique())
print(ncr["Cancellation_Reason_Driver"].dropna().unique())

['Driver Not Moving' 'Driver Asked to Cancel' 'Change of Plans'
 'Wrong Address']
['Driver Not Moving' 'Driver Asked to Cancel' 'AC Issue' 'Change of Plans'
 'Wrong Address']
['Car Issue' 'Customer Sick' 'Customer Issue' 'Over Capacity']
['Car Issue' 'Customer Issue' 'Over Capacity' 'Customer Sick']

In [55]:
ncr["Booking_ID"] = ncr["Booking_ID"].str.strip().str.replace('"', '', regex=False)
ncr["Customer_ID"] = ncr["Customer_ID"].str.strip().str.replace('"', '', regex=False)

In [56]:
print("Bangalore Sample:")
display(bangalore.sample(50))

print("\nNCR Sample:")
display(ncr.sample(50))

Bangalore Sample:

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Cancelled_By_Driver,Cancellation_Reason_Customer,Cancellation_Reason_Driver,Incomplete_Rides,Incomplete_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Rating,Customer_Rating
99069,2024-07-27,10:38:00,CNR5138443837,Completed,CID371922,Prime Sedan,Yelahanka,Varthur,42.0,70.0,...,0,NaN,NaN,0,NaN,574,Cash,32,4.9,3.4
67974,2024-07-15,08:19:00,CNR7948531033,No Driver Found,CID595025,eBike,Hennur,Yelahanka,NaN,NaN,...,0,NaN,NaN,0,NaN,214,Unknown,0,NaN,NaN
101993,2024-07-31,18:56:00,CNR1269221209,Completed,CID214932,eBike,KR Puram,Frazer Town,105.0,40.0,...,0,NaN,NaN,1,Other Issue,421,Cash,31,3.7,4.4
240,2024-07-06,07:14:00,CNR8826275068,Completed,CID257693,Prime Sedan,Richmond Town,Tumkur Road,252.0,65.0,...,0,NaN,NaN,0,NaN,161,Cash,5,4.1,4.0
20463,2024-07-02,01:20:00,CNR8388002138,Completed,CID371496,Mini,Cox Town,Shivajinagar,203.0,120.0,...,0,NaN,NaN,0,NaN,156,Cash,24,4.6,4.5
29566,2024-07-11,04:33:00,CNR3467047522,Completed,CID299149,Mini,Yeshwanthpur,Bannerghatta Road,308.0,40.0,...,0,NaN,NaN,1,Customer Demand,245,Cash,44,3.9,4.8
48599,2024-07-02,23:07:00,CNR4072141015,Completed,CID343200,Prime SUV,Sahakar Nagar,Koramangala,196.0,40.0,...,0,NaN,NaN,0,NaN,490,UPI,17,3.4,3.1
29694,2024-07-15,05:43:00,CNR7815116518,Completed,CID333016,Mini,Frazer Town,Magadi Road,126.0,25.0,...,0,NaN,NaN,0,NaN,231,Unknown,3,4.8,4.7
31241,2024-07-10,19:46:00,CNR3508791661,Completed,CID110068,eBike,Electronic City,Ramamurthy Nagar,224.0,95.0,...,0,NaN,NaN,0,NaN,923,Cash,24,3.4,3.6
38798,2024-07-04,04:30:00,CNR1568512415,No Driver Found,CID213966,Mini,Whitefield,Richmond Town,NaN,NaN,...,0,NaN,NaN,0,NaN,349,Unknown,0,NaN,NaN
385,2024-07-03,20:40:00,CNR9545114159,Cancelled by Driver,CID576096,Prime Plus,BTM Layout,Frazer Town,NaN,NaN,...,1,NaN,Customer Issue,0,NaN,1501,Unknown,0,NaN,NaN
74607,2024-07-19,12:53:00,CNR8167203444,Completed,CID310898,Prime Plus,BTM Layout,Rajarajeshwari Nagar,77.0,110.0,...,0,NaN,NaN,0,NaN,327,Cash,45,4.3,3.4
102059,2024-07-31,17:50:00,CNR1581121574,Completed,CID859491,Prime Sedan,Devanahalli,Yeshwanthpur,252.0,75.0,...,0,NaN,NaN,0,NaN,423,UPI,33,3.6,4.1
50039,2024-07-20,05:15:00,CNR4691839985,Completed,CID416103,Prime Plus,Yeshwanthpur,Whitefield,119.0,55.0,...,0,NaN,NaN,0,NaN,568,Cash,19,4.4,3.5
59587,2024-07-27,09:36:00,CNR8732519185,Completed,CID862265,Prime SUV,Ramamurthy Nagar,Tumkur Road,287.0,90.0,...,0,NaN,NaN,0,NaN,439,UPI,43,3.8,4.5
101742,2024-07-31,17:50:00,CNR1486761475,No Driver Found,CID121862,eBike,Electronic City,Malleshwaram,NaN,NaN,...,0,NaN,NaN,0,NaN,206,Unknown,0,NaN,NaN
64516,2024-07-24,16:38:00,CNR8467780334,Completed,CID917437,Prime Plus,Hennur,MG Road,287.0,115.0,...,0,NaN,NaN,0,NaN,185,UPI,7,3.8,3.6
23564,2024-07-12,02:07:00,CNR4399302411,Completed,CID393225,Mini,Shantinagar,Jayanagar,273.0,35.0,...,0,NaN,NaN,0,NaN,447,UPI,2,3.4,3.4
41666,2024-07-14,17:02:00,CNR6453595100,Completed,CID161164,Prime Sedan,Richmond Town,Ulsoor,175.0,25.0,...,0,NaN,NaN,0,NaN,456,UPI,38,3.0,4.9
14578,2024-07-17,23:50:00,CNR1643257013,Completed,CID181467,Auto,Kengeri,Langford Town,154.0,145.0,...,0,NaN,NaN,0,NaN,1056,Cash,1,3.2,5.0
8566,2024-07-27,21:19:00,CNR6425248405,Completed,CID711615,Mini,Chickpet,Koramangala,266.0,95.0,...,0,NaN,NaN,1,Other Issue,253,Cash,44,4.7,3.9
72362,2024-07-02,06:23:00,CNR9560383322,Cancelled by Driver,CID458333,Auto,Vijayanagar,Kammanahalli,NaN,NaN,...,1,NaN,Customer Issue,0,NaN,153,Unknown,0,NaN,NaN
10685,2024-07-30,14:52:00,CNR1669418368,Completed,CID918457,Auto,Hosur Road,Padmanabhanagar,287.0,30.0,...,0,NaN,NaN,0,NaN,968,UPI,13,3.5,4.6
101252,2024-07-31,14:51:00,CNR8860478803,Completed,CID421696,Prime Plus,Langford Town,Varthur,259.0,25.0,...,0,NaN,NaN,0,NaN,812,UPI,4,3.1,4.9
69095,2024-07-06,04:50:00,CNR1177504874,Cancelled by Driver,CID340856,eBike,Tumkur Road,Magadi Road,NaN,NaN,...,1,NaN,Over Capacity,0,NaN,221,Unknown,0,NaN,NaN
98877,2024-07-28,13:21:00,CNR7474994203,Completed,CID776582,Auto,Mysore Road,Marathahalli,168.0,50.0,...,0,NaN,NaN,0,NaN,2224,Cash,12,3.3,4.6
78357,2024-07-06,06:19:00,CNR7937498022,Completed,CID903947,Auto,Bannerghatta Road,Bellandur,210.0,100.0,...,0,NaN,NaN,1,Customer Demand,136,Cash,6,4.0,4.2
95690,2024-07-07,20:35:00,CNR2070684700,No Driver Found,CID284789,Prime SUV,Bellandur,Whitefield,NaN,NaN,...,0,NaN,NaN,0,NaN,2532,Unknown,0,NaN,NaN
10540,2024-07-23,00:28:00,CNR5051759117,Completed,CID261522,Mini,Jayanagar,Richmond Town,294.0,50.0,...,0,NaN,NaN,0,NaN,138,UPI,14,3.9,4.0
50584,2024-07-15,03:05:00,CNR6339105602,Completed,CID992214,Prime Sedan,Tumkur Road,Nagarbhavi,224.0,80.0,...,0,NaN,NaN,0,NaN,484,Cash,35,4.1,4.9
72579,2024-07-02,12:13:00,CNR7497656079,Completed,CID246016,eBike,Tumkur Road,Rajajinagar,287.0,100.0,...,0,NaN,NaN,0,NaN,874,UPI,1,4.0,4.6
101676,2024-07-31,18:47:00,CNR6410226443,Completed,CID407267,Prime Sedan,MG Road,Hebbal,84.0,120.0,...,0,NaN,NaN,0,NaN,204,UPI,31,4.1,4.2
4777,2024-07-26,03:33:00,CNR9246456516,No Driver Found,CID183764,Prime Sedan,Chickpet,Whitefield,NaN,NaN,...,0,NaN,NaN,0,NaN,525,Unknown,0,NaN,NaN
87590,2024-07-22,12:02:00,CNR2702838073,Completed,CID556913,Bike,Varthur,Richmond Town,70.0,80.0,...,0,NaN,NaN,0,NaN,2103,UPI,13,4.3,3.9
97859,2024-07-29,02:54:00,CNR5273562202,Completed,CID253464,eBike,Kammanahalli,MG Road,133.0,50.0,...,0,NaN,NaN,0,NaN,296,Cash,8,3.0,3.9
52653,2024-07-12,12:31:00,CNR9983161703,Cancelled by Driver,CID918574,Bike,Richmond Town,Kadugodi,NaN,NaN,...,1,NaN,Customer Issue,0,NaN,438,Unknown,0,NaN,NaN
68730,2024-07-08,13:25:00,CNR2370657510,Completed,CID246691,Auto,Bellandur,Bellandur,196.0,95.0,...,0,NaN,NaN,0,NaN,1123,Cash,7,4.6,4.5
63592,2024-07-07,01:03:00,CNR4248853058,Completed,CID731287,Prime SUV,Magadi Road,Padmanabhanagar,210.0,105.0,...,0,NaN,NaN,0,NaN,236,UPI,8,3.3,3.5
93740,2024-07-29,09:02:00,CNR2829428722,Completed,CID585768,eBike,Koramangala,Varthur,119.0,115.0,...,0,NaN,NaN,0,NaN,218,Cash,44,3.4,4.1
37912,2024-07-09,16:58:00,CNR3420952109,Completed,CID563350,Prime Sedan,Jayanagar,MG Road,182.0,135.0,...,0,NaN,NaN,0,NaN,301,UPI,19,3.3,4.7
21599,2024-07-12,12:34:00,CNR2697175569,Completed,CID792586,Mini,Shantinagar,Indiranagar,301.0,80.0,...,0,NaN,NaN,0,NaN,2030,UPI,10,3.2,4.9
11870,2024-07-14,18:46:00,CNR2529258657,Completed,CID172396,Prime SUV,Vijayanagar,Sarjapur Road,231.0,25.0,...,0,NaN,NaN,0,NaN,330,Cash,27,4.1,3.8
13452,2024-07-05,17:06:00,CNR1663460325,Cancelled by Driver,CID451237,Prime SUV,Nagarbhavi,Ulsoor,NaN,NaN,...,1,NaN,Customer Issue,0,NaN,909,Unknown,0,NaN,NaN
70128,2024-07-02,23:57:00,CNR2534493206,No Driver Found,CID319714,Prime Sedan,Mysore Road,Hebbal,NaN,NaN,...,0,NaN,NaN,0,NaN,397,Unknown,0,NaN,NaN
88298,2024-07-08,11:55:00,CNR4935771134,Completed,CID613468,Mini,Yelahanka,Majestic,259.0,80.0,...,0,NaN,NaN,0,NaN,532,Cash,20,3.7,4.1
85875,2024-07-15,14:48:00,CNR2153873365,Completed,CID892216,Bike,Kadugodi,Padmanabhanagar,203.0,70.0,...,0,NaN,NaN,0,NaN,198,UPI,24,4.3,4.1
23237,2024-07-20,11:54:00,CNR7947273660,Completed,CID994566,Prime Plus,Indiranagar,Kadugodi,294.0,30.0,...,0,NaN,NaN,0,NaN,103,Cash,44,4.3,4.3
18305,2024-07-18,01:34:00,CNR2467000144,No Driver Found,CID681289,Mini,Basavanagudi,Majestic,NaN,NaN,...,0,NaN,NaN,0,NaN,167,Unknown,0,NaN,NaN
92913,2024-07-14,15:38:00,CNR5075441718,Completed,CID725601,Prime Plus,Shantinagar,Yeshwanthpur,154.0,120.0,...,0,NaN,NaN,0,NaN,200,Cash,33,4.3,4.5
65464,2024-07-04,01:50:00,CNR2842522044,Cancelled by Customer,CID524823,Bike,Hebbal,Richmond Town,NaN,NaN,...,0,Driver Not Moving,NaN,0,NaN,496,Unknown,0,NaN,NaN

NCR Sample:

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Cancellation_Reason_Customer,Cancelled_By_Driver,Cancellation_Reason_Driver,Incomplete_Rides,Incomplete_Reason,Booking_Value,Ride_Distance,Driver_Rating,Customer_Rating,Payment_Method
54956,2024-12-05,23:16:37,CNR1241974,Completed,CID2520711,Bike,Govindpuri,Narsinghpur,9.9,28.4,...,NaN,0,NaN,0,NaN,213.0,41.61,4.7,5.0,Card
9056,2024-11-18,13:56:00,CNR4370958,Cancelled by Driver,CID1577516,Premier Sedan,Kherki Daula Toll,Pataudi Chowk,5.1,NaN,...,NaN,1,Over Capacity,0,NaN,NaN,NaN,NaN,NaN,Unknown
94732,2024-12-19,15:04:41,CNR9000350,Cancelled by Customer,CID5932826,Bike,Ramesh Nagar,India Gate,9.7,NaN,...,Change of Plans,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
23697,2024-12-11,08:09:10,CNR5078962,Completed,CID2815668,Bike,Moolchand,Hauz Rani,11.6,19.8,...,NaN,0,NaN,0,NaN,974.0,28.99,4.3,3.9,Card
37879,2024-06-17,19:01:02,CNR6081086,Cancelled by Customer,CID7596763,Bike,Golf Course Road,Moolchand,11.0,NaN,...,Driver Not Moving,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
140264,2024-10-09,15:28:54,CNR9567663,Completed,CID4851975,Go Sedan,Udyog Vihar Phase 4,Malviya Nagar,4.8,21.0,...,NaN,0,NaN,0,NaN,708.0,26.08,3.9,5.0,Cash
110007,2024-06-05,22:52:59,CNR3316882,Cancelled by Driver,CID9915276,Bike,Central Secretariat,Lajpat Nagar,7.0,NaN,...,NaN,1,Customer Sick,0,NaN,NaN,NaN,NaN,NaN,Unknown
25556,2024-02-11,14:51:34,CNR2464164,Completed,CID4264158,Go Mini,Vishwavidyalaya,Azadpur,9.1,37.5,...,NaN,0,NaN,0,NaN,405.0,15.93,3.4,4.8,Card
129431,2024-07-13,18:55:55,CNR3953560,Completed,CID7222278,Bike,Kashmere Gate,Badarpur,10.9,26.4,...,NaN,0,NaN,0,NaN,1894.0,14.93,5.0,4.8,UPI
3094,2024-12-08,14:36:44,CNR5465695,Completed,CID2904781,Go Mini,Gwal Pahari,Panchsheel Park,6.2,17.1,...,NaN,0,NaN,0,NaN,482.0,19.89,4.9,5.0,UPI
8347,2024-08-30,02:51:09,CNR9649612,Completed,CID1755301,eBike,Khandsa,Kashmere Gate,4.7,36.7,...,NaN,0,NaN,0,NaN,691.0,19.34,3.8,4.9,Cash
38158,2024-12-18,10:50:32,CNR9647251,Completed,CID8101280,Go Mini,Munirka,Vaishali,11.2,38.8,...,NaN,0,NaN,0,NaN,114.0,20.32,3.9,4.9,UPI
91988,2024-04-22,07:58:36,CNR5739264,Completed,CID8157885,Go Mini,South Extension,Tis Hazari,5.4,35.5,...,NaN,0,NaN,0,NaN,243.0,8.12,4.6,4.9,Cash
147398,2024-04-05,23:11:32,CNR6179595,Completed,CID5538733,Auto,Greater Kailash,Nehru Place,4.5,32.9,...,NaN,0,NaN,0,NaN,775.0,39.52,4.2,4.8,Card
8225,2024-05-07,15:17:06,CNR5194803,Cancelled by Customer,CID8563237,Go Mini,Okhla,Uttam Nagar,13.6,NaN,...,Wrong Address,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
124243,2024-02-06,07:03:10,CNR9932393,Completed,CID3846307,Go Sedan,Jasola,Laxmi Nagar,3.1,43.5,...,NaN,0,NaN,0,NaN,86.0,4.36,4.7,4.4,UPI
99332,2024-08-16,09:24:11,CNR1478192,Completed,CID8676196,Auto,Botanical Garden,Noida Extension,2.7,43.9,...,NaN,0,NaN,0,NaN,240.0,49.60,3.8,5.0,Card
91355,2024-08-18,19:47:37,CNR1985382,Completed,CID6251019,Auto,Shastri Nagar,Golf Course Road,14.1,37.5,...,NaN,0,NaN,0,NaN,217.0,34.71,4.3,3.8,UPI
86668,2024-03-07,06:04:14,CNR2607345,Completed,CID7027297,Bike,Model Town,Ramesh Nagar,14.8,20.6,...,NaN,0,NaN,0,NaN,302.0,42.57,5.0,3.9,UPI
29350,2024-06-29,18:33:53,CNR4331719,Completed,CID1382533,Go Sedan,Ashok Park Main,India Gate,8.6,31.6,...,NaN,0,NaN,0,NaN,680.0,4.88,4.2,3.4,Cash
63493,2024-10-11,16:55:31,CNR6714123,Completed,CID1016195,Uber XL,Sonipat,Khandsa,5.1,19.2,...,NaN,0,NaN,0,NaN,926.0,6.85,3.6,4.9,UPI
38674,2024-12-17,09:04:47,CNR9693536,Completed,CID2499752,Auto,Cyber Hub,Rajouri Garden,5.5,27.1,...,NaN,0,NaN,0,NaN,448.0,2.09,3.8,4.0,Cash
73485,2024-11-22,10:09:53,CNR8290752,Completed,CID1835847,Go Mini,Ashok Park Main,Noida Film City,14.7,34.4,...,NaN,0,NaN,0,NaN,466.0,13.07,4.1,4.8,UPI
60652,2024-11-17,06:09:03,CNR6607979,Completed,CID7449548,Auto,Ashok Park Main,Barakhamba Road,3.5,35.8,...,NaN,0,NaN,0,NaN,181.0,2.02,4.3,4.7,Card
116427,2024-07-16,20:16:25,CNR3941037,Cancelled by Customer,CID3600877,eBike,Shastri Nagar,Khandsa,10.6,NaN,...,Driver Asked to Cancel,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
87605,2024-07-03,19:23:23,CNR1041860,Cancelled by Customer,CID8416905,Auto,Mayur Vihar,INA Market,6.5,NaN,...,Wrong Address,0,NaN,0,NaN,NaN,NaN,NaN,NaN,Unknown
104754,2024-03-09,18:47:37,CNR8318427,Cancelled by Driver,CID7382505,Bike,Nehru Place,Sohna Road,3.3,NaN,...,NaN,1,Customer Issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
112069,2024-11-05,14:59:19,CNR3143536,Completed,CID7341483,Go Sedan,Kaushambi,IFFCO Chowk,6.8,36.2,...,NaN,0,NaN,0,NaN,819.0,26.30,3.8,4.9,UPI
3646,2024-10-13,19:48:43,CNR3762020,Cancelled by Driver,CID7018748,Auto,Golf Course Road,Ambience Mall,7.0,NaN,...,NaN,1,Car Issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
63457,2024-09-07,20:27:23,CNR2677240,Cancelled by Driver,CID5872103,Uber XL,Khandsa,ITO,4.3,NaN,...,NaN,1,Customer Issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
64503,2024-04-21,10:54:31,CNR6414273,Completed,CID1154234,Auto,Chirag Delhi,Ashram,13.7,44.4,...,NaN,0,NaN,0,NaN,558.0,32.14,4.1,4.6,Card
34479,2024-05-03,01:32:36,CNR8348677,Cancelled by Driver,CID7710383,eBike,Chirag Delhi,Mundka,9.1,NaN,...,NaN,1,Over Capacity,0,NaN,NaN,NaN,NaN,NaN,Unknown
79527,2024-01-22,19:03:19,CNR6565266,Completed,CID9393246,Go Mini,Sadar Bazar Gurgaon,Green Park,7.9,19.8,...,NaN,0,NaN,0,NaN,466.0,42.78,4.3,4.2,Card
110506,2024-12-18,06:45:07,CNR2682784,Incomplete,CID4726312,Go Mini,Rajiv Nagar,Rohini West,6.1,11.6,...,NaN,0,NaN,1,Customer Demand,77.0,19.28,NaN,NaN,Card
42514,2024-11-03,19:10:51,CNR7433762,Completed,CID5959459,Premier Sedan,Panipat,Bhikaji Cama Place,2.4,25.5,...,NaN,0,NaN,0,NaN,1449.0,43.23,4.8,4.8,UPI
98590,2024-06-05,13:55:01,CNR3361772,Completed,CID6910432,Auto,RK Puram,Chirag Delhi,5.7,44.1,...,NaN,0,NaN,0,NaN,872.0,26.34,3.6,3.2,UPI
95974,2024-06-22,21:17:48,CNR4514976,Completed,CID7283039,Go Sedan,Faridabad Sector 15,Samaypur Badli,5.0,31.1,...,NaN,0,NaN,0,NaN,1122.0,23.72,4.2,3.8,Cash
68064,2024-05-01,18:48:40,CNR7526138,Completed,CID7818428,Bike,Ashok Park Main,Kirti Nagar,14.2,31.8,...,NaN,0,NaN,0,NaN,404.0,43.94,3.2,4.7,Card
97368,2024-12-01,21:51:15,CNR7902500,Completed,CID8331544,Go Sedan,Sultanpur,Satguru Ram Singh Marg,3.2,37.9,...,NaN,0,NaN,0,NaN,130.0,16.66,4.3,4.3,Card
71246,2024-07-28,03:28:44,CNR5231720,Completed,CID5613679,Bike,IGNOU Road,Kanhaiya Nagar,3.3,29.3,...,NaN,0,NaN,0,NaN,628.0,43.75,4.7,4.3,Cash
2803,2024-07-16,16:21:20,CNR3510366,Cancelled by Driver,CID3378836,Premier Sedan,Qutub Minar,Manesar,4.5,NaN,...,NaN,1,Customer Sick,0,NaN,NaN,NaN,NaN,NaN,Unknown
100494,2024-08-02,08:41:03,CNR9579306,Completed,CID3884555,Bike,IMT Manesar,Tagore Garden,11.0,38.2,...,NaN,0,NaN,0,NaN,390.0,36.31,4.1,4.2,UPI
123857,2024-01-09,19:57:24,CNR1798762,Completed,CID5398967,Go Sedan,Shivaji Park,DLF Phase 3,5.1,38.0,...,NaN,0,NaN,0,NaN,640.0,28.91,3.9,4.2,Wallet
78308,2024-04-23,22:35:22,CNR9148927,Completed,CID5678350,Go Sedan,Ashok Park Main,Huda City Centre,3.9,26.0,...,NaN,0,NaN,0,NaN,106.0,11.34,4.2,5.0,UPI
68073,2024-05-24,17:28:25,CNR1152934,Completed,CID3756277,Auto,Palam Vihar,Govindpuri,7.3,27.7,...,NaN,0,NaN,0,NaN,366.0,7.82,5.0,3.9,Cash
81894,2024-03-10,08:41:39,CNR8585544,Cancelled by Driver,CID3658141,Auto,Vasant Kunj,Sarai Kale Khan,7.9,NaN,...,NaN,1,Over Capacity,0,NaN,NaN,NaN,NaN,NaN,Unknown
145443,2024-08-30,01:15:30,CNR9626235,Cancelled by Driver,CID7062292,Bike,Panchsheel Park,Yamuna Bank,9.6,NaN,...,NaN,1,Customer Issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
80029,2024-04-16,09:24:37,CNR7743029,Cancelled by Driver,CID1365430,Auto,Inderlok,GTB Nagar,8.9,NaN,...,NaN,1,Customer Issue,0,NaN,NaN,NaN,NaN,NaN,Unknown
37516,2024-03-22,03:46:08,CNR4098712,Completed,CID6505318,Auto,Nehru Place,DLF Phase 3,13.7,43.7,...,NaN,0,NaN,0,NaN,349.0,29.99,4.2,4.3,Wallet
67879,2024-07-30,13:20:23,CNR3936157,Cancelled by Driver,CID7430721,Go Mini,Tis Hazari,Civil Lines Gurgaon,6.9,NaN,...,NaN,1,Over Capacity,0,NaN,NaN,NaN,NaN,NaN,Unknown

In [57]:
bangalore.to_csv("cleaned_bangalore.csv", index=False)
ncr.to_csv("cleaned_ncr.csv", index=False)

In [58]:
from google.colab import files

files.download("cleaned_bangalore.csv")

In [59]:
files.download("cleaned_ncr.csv")

In [60]:
bangalore["City"] = "Bangalore"

In [61]:
ncr["City"] = "NCR"

In [62]:
files.download("cleaned_bangalore.csv")

In [63]:
bangalore.to_csv("cleaned_bangalore.csv", index=False)
ncr.to_csv("cleaned_ncr.csv", index=False)

In [64]:
files.download("cleaned_bangalore.csv")

In [65]:
files.download("cleaned_ncr.csv")

In [66]:
combined_df = pd.concat([bangalore, ncr], ignore_index=True)

In [67]:
combined_df["City"].value_counts()

City
NCR          150000
Bangalore    103024
Name: count, dtype: int64

In [68]:
combined_df.shape

(253024, 22)

In [69]:
combined_df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'VTAT', 'CTAT',
       'Cancelled_By_Customer', 'Cancelled_By_Driver',
       'Cancellation_Reason_Customer', 'Cancellation_Reason_Driver',
       'Incomplete_Rides', 'Incomplete_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Rating', 'Customer_Rating',
       'City'],
      dtype='object')

In [70]:
combined_df.isnull().sum()

Date                                 0
Time                                 0
Booking_ID                           0
Booking_Status                       0
Customer_ID                          0
Vehicle_Type                         0
Pickup_Location                      0
Drop_Location                        0
VTAT                             49557
CTAT                             87057
Cancelled_By_Customer                0
Cancelled_By_Driver                  0
Cancellation_Reason_Customer    233593
Cancellation_Reason_Driver      207590
Incomplete_Rides                     0
Incomplete_Reason               240098
Booking_Value                    48000
Payment_Method                       0
Ride_Distance                    48000
Driver_Rating                    96057
Customer_Rating                  96057
City                                 0
dtype: int64

In [71]:
combined_df["Booking_Status"].unique()

array(['Cancelled by Driver', 'Completed', 'Cancelled by Customer',
       'No Driver Found', 'Incomplete'], dtype=object)

In [72]:
combined_df["Payment_Method"].unique()

array(['Unknown', 'Cash', 'UPI', 'Card', 'Wallet'], dtype=object)

In [73]:
combined_df["Incomplete_Rides"].unique()

array([0, 1])

In [74]:
combined_df["Cancelled_By_Customer"].unique()
combined_df["Cancelled_By_Driver"].unique()

array([1, 0])

In [75]:
combined_df[
    (combined_df["Cancelled_By_Customer"] == 0) &
    (combined_df["Cancellation_Reason_Customer"].notnull())
]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, VTAT, CTAT, Cancelled_By_Customer, Cancelled_By_Driver, Cancellation_Reason_Customer, Cancellation_Reason_Driver, Incomplete_Rides, Incomplete_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Rating, Customer_Rating, City]
Index: []

[0 rows x 22 columns]

In [76]:
combined_df[
    (combined_df["Incomplete_Rides"] == 0) &
    (combined_df["Incomplete_Reason"].notnull())
]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, VTAT, CTAT, Cancelled_By_Customer, Cancelled_By_Driver, Cancellation_Reason_Customer, Cancellation_Reason_Driver, Incomplete_Rides, Incomplete_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Rating, Customer_Rating, City]
Index: []

[0 rows x 22 columns]

In [77]:
combined_df.duplicated().sum()

np.int64(0)

In [78]:
combined_df.dtypes

Date                             object
Time                             object
Booking_ID                       object
Booking_Status                   object
Customer_ID                      object
Vehicle_Type                     object
Pickup_Location                  object
Drop_Location                    object
VTAT                            float64
CTAT                            float64
Cancelled_By_Customer             int64
Cancelled_By_Driver               int64
Cancellation_Reason_Customer     object
Cancellation_Reason_Driver       object
Incomplete_Rides                  int64
Incomplete_Reason                object
Booking_Value                   float64
Payment_Method                   object
Ride_Distance                   float64
Driver_Rating                   float64
Customer_Rating                 float64
City                             object
dtype: object

In [79]:
combined_df["Date"] = pd.to_datetime(combined_df["Date"], errors='coerce')

In [80]:
combined_df["Time"] = pd.to_datetime(combined_df["Time"], errors='coerce').dt.time

In [81]:
combined_df["Booking_ID"] = combined_df["Booking_ID"].astype(str)
combined_df["Customer_ID"] = combined_df["Customer_ID"].astype(str)

In [82]:
combined_df.dtypes

Date                            datetime64[ns]
Time                                    object
Booking_ID                              object
Booking_Status                          object
Customer_ID                             object
Vehicle_Type                            object
Pickup_Location                         object
Drop_Location                           object
VTAT                                   float64
CTAT                                   float64
Cancelled_By_Customer                    int64
Cancelled_By_Driver                      int64
Cancellation_Reason_Customer            object
Cancellation_Reason_Driver              object
Incomplete_Rides                         int64
Incomplete_Reason                       object
Booking_Value                          float64
Payment_Method                          object
Ride_Distance                          float64
Driver_Rating                          float64
Customer_Rating                        float64
City                                    object
dtype: object

In [83]:
# Create DateTime column
combined_df["DateTime"] = pd.to_datetime(
    combined_df["Date"].astype(str) + " " + combined_df["Time"].astype(str),
    errors="coerce"
)

# Drop old columns
combined_df.drop(columns=["Date", "Time"], inplace=True)

/tmp/ipykernel_1202/2437277304.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  combined_df["DateTime"] = pd.to_datetime(

In [84]:
combined_df["DateTime"].dtype

dtype('<M8[ns]')

In [86]:
combined_df["Hour"] = combined_df["DateTime"].dt.hour
combined_df["Day"] = combined_df["DateTime"].dt.day
combined_df["Month"] = combined_df["DateTime"].dt.month
combined_df["Weekday"] = combined_df["DateTime"].dt.day_name()

In [87]:
combined_df.shape

(253024, 25)

In [88]:
combined_df.to_csv("final_rides_data.csv", index=False)

In [89]:
from google.colab import files
files.download("final_rides_data.csv")

In [90]:
combined_df[combined_df["City"] == "Bangalore"][["DateTime"]].head()

  DateTime
0      NaT
1      NaT
2      NaT
3      NaT
4      NaT

In [91]:
bangalore["Date"] = pd.to_datetime(bangalore["Date"], errors='coerce')
bangalore["Time"] = bangalore["Date"].dt.time
bangalore["Date"] = bangalore["Date"].dt.date

In [92]:
bangalore["DateTime"] = pd.to_datetime(
    bangalore["Date"].astype(str) + " " + bangalore["Time"].astype(str),
    errors="coerce"
)

ncr["DateTime"] = pd.to_datetime(
    ncr["Date"].astype(str) + " " + ncr["Time"].astype(str),
    errors="coerce"
)

In [93]:
combined_df = pd.concat([bangalore, ncr], ignore_index=True)

In [94]:
combined_df[combined_df["City"] == "Bangalore"]["DateTime"].isnull().sum()

np.int64(0)

In [95]:
combined_df.groupby("City")["DateTime"].apply(lambda x: x.isnull().sum())

City
Bangalore    0
NCR          0
Name: DateTime, dtype: int64

In [96]:
combined_df.shape

(253024, 23)

In [97]:
combined_df["City"].value_counts()

City
NCR          150000
Bangalore    103024
Name: count, dtype: int64

In [98]:
combined_df["Booking_Status"].unique()

array(['Cancelled by Driver', 'Completed', 'Cancelled by Customer',
       'No Driver Found', 'Incomplete'], dtype=object)

In [99]:
combined_df[
    (combined_df["Cancelled_By_Customer"] == 0) &
    (combined_df["Cancellation_Reason_Customer"].notnull())
]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, VTAT, CTAT, Cancelled_By_Customer, Cancelled_By_Driver, Cancellation_Reason_Customer, Cancellation_Reason_Driver, Incomplete_Rides, Incomplete_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Rating, Customer_Rating, City, DateTime]
Index: []

[0 rows x 23 columns]

In [100]:
combined_df[
    (combined_df["Incomplete_Rides"] == 0) &
    (combined_df["Incomplete_Reason"].notnull())
]

Empty DataFrame
Columns: [Date, Time, Booking_ID, Booking_Status, Customer_ID, Vehicle_Type, Pickup_Location, Drop_Location, VTAT, CTAT, Cancelled_By_Customer, Cancelled_By_Driver, Cancellation_Reason_Customer, Cancellation_Reason_Driver, Incomplete_Rides, Incomplete_Reason, Booking_Value, Payment_Method, Ride_Distance, Driver_Rating, Customer_Rating, City, DateTime]
Index: []

[0 rows x 23 columns]

In [101]:
combined_df.duplicated().sum()

np.int64(0)

In [102]:
combined_df.dtypes

Date                                    object
Time                                    object
Booking_ID                              object
Booking_Status                          object
Customer_ID                             object
Vehicle_Type                            object
Pickup_Location                         object
Drop_Location                           object
VTAT                                   float64
CTAT                                   float64
Cancelled_By_Customer                    int64
Cancelled_By_Driver                      int64
Cancellation_Reason_Customer            object
Cancellation_Reason_Driver              object
Incomplete_Rides                         int64
Incomplete_Reason                       object
Booking_Value                          float64
Payment_Method                          object
Ride_Distance                          float64
Driver_Rating                          float64
Customer_Rating                        float64
City                                    object
DateTime                        datetime64[ns]
dtype: object

In [103]:
combined_df.sample(20)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Cancellation_Reason_Driver,Incomplete_Rides,Incomplete_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Rating,Customer_Rating,City,DateTime
31116,2024-07-16,00:00:00,CNR2941509263,No Driver Found,CID979208,Auto,Majestic,Richmond Town,NaN,NaN,...,NaN,0,NaN,413.0,Unknown,0.00,NaN,NaN,Bangalore,2024-07-16 00:00:00
160707,2024-10-02 00:00:00,17:50:03,CNR3363475,Completed,CID1421200,Auto,Rohini East,Samaypur Badli,6.0,17.1,...,NaN,0,NaN,301.0,Cash,12.82,4.2,4.9,NCR,2024-10-02 17:50:03
207731,2024-04-21 00:00:00,08:16:26,CNR6410830,Completed,CID9843929,Bike,Patel Chowk,Mundka,5.2,20.4,...,NaN,0,NaN,157.0,UPI,37.32,4.0,4.3,NCR,2024-04-21 08:16:26
230999,2024-09-02 00:00:00,08:56:25,CNR5403342,Completed,CID6959923,eBike,Vishwavidyalaya,India Gate,13.8,26.4,...,NaN,0,NaN,876.0,UPI,40.98,4.3,3.1,NCR,2024-09-02 08:56:25
87453,2024-07-06,00:00:00,CNR7837712836,Cancelled by Customer,CID489497,Bike,Banashankari,Yeshwanthpur,NaN,NaN,...,NaN,0,NaN,768.0,Unknown,0.00,NaN,NaN,Bangalore,2024-07-06 00:00:00
145562,2024-04-18 00:00:00,10:52:03,CNR2841066,Completed,CID1157466,Go Mini,Delhi Gate,Shastri Park,13.2,22.6,...,NaN,0,NaN,338.0,UPI,8.16,4.2,3.9,NCR,2024-04-18 10:52:03
221211,2024-12-30 00:00:00,18:37:03,CNR8810238,Cancelled by Customer,CID9868826,Go Mini,Barakhamba Road,Chanakyapuri,19.4,NaN,...,NaN,0,NaN,NaN,Unknown,NaN,NaN,NaN,NCR,2024-12-30 18:37:03
127484,2024-09-26 00:00:00,15:54:45,CNR5766114,Cancelled by Driver,CID2000987,Go Sedan,India Gate,Karkarduma,9.1,NaN,...,Car Issue,0,NaN,NaN,Unknown,NaN,NaN,NaN,NCR,2024-09-26 15:54:45
92505,2024-07-18,00:00:00,CNR2044399916,Cancelled by Driver,CID480781,Mini,Sarjapur Road,MG Road,NaN,NaN,...,Customer Sick,0,NaN,1726.0,Unknown,0.00,NaN,NaN,Bangalore,2024-07-18 00:00:00
134497,2024-02-27 00:00:00,13:13:54,CNR5739917,Completed,CID4278828,Premier Sedan,Hauz Khas,Pragati Maidan,4.6,39.9,...,NaN,0,NaN,296.0,Card,2.94,4.7,3.4,NCR,2024-02-27 13:13:54
214712,2024-09-06 00:00:00,19:45:14,CNR9219494,Completed,CID3509762,Premier Sedan,Greater Kailash,Maidan Garhi,12.3,38.5,...,NaN,0,NaN,136.0,UPI,34.53,4.5,4.5,NCR,2024-09-06 19:45:14
36493,2024-07-22,00:00:00,CNR7709693126,Completed,CID570330,Auto,Whitefield,Frazer Town,70.0,90.0,...,NaN,0,NaN,357.0,UPI,12.00,4.8,3.7,Bangalore,2024-07-22 00:00:00
189677,2024-10-06 00:00:00,18:00:01,CNR5226427,Cancelled by Driver,CID5548891,Go Mini,Greater Noida,Model Town,9.0,NaN,...,Over Capacity,0,NaN,NaN,Unknown,NaN,NaN,NaN,NCR,2024-10-06 18:00:01
11145,2024-07-13,00:00:00,CNR6476217096,Cancelled by Driver,CID441810,Auto,Hosur Road,Sarjapur Road,NaN,NaN,...,Car Issue,0,NaN,125.0,Unknown,0.00,NaN,NaN,Bangalore,2024-07-13 00:00:00
151450,2024-12-22 00:00:00,18:16:53,CNR6024650,Completed,CID1798700,Auto,Noida Film City,Dwarka Mor,4.3,34.6,...,NaN,0,NaN,308.0,UPI,4.62,4.6,4.9,NCR,2024-12-22 18:16:53
95513,2024-07-18,00:00:00,CNR3359377973,Completed,CID467079,Bike,Kengeri,KR Puram,147.0,30.0,...,NaN,0,NaN,385.0,UPI,38.00,4.8,3.3,Bangalore,2024-07-18 00:00:00
53869,2024-07-10,00:00:00,CNR9142782569,Completed,CID565339,Prime SUV,Richmond Town,Indiranagar,175.0,140.0,...,NaN,0,NaN,313.0,Cash,11.00,3.0,4.8,Bangalore,2024-07-10 00:00:00
244080,2024-04-28 00:00:00,08:11:58,CNR5040319,Completed,CID5325730,Premier Sedan,Patel Chowk,Mansarovar Park,11.0,38.4,...,NaN,0,NaN,1091.0,Cash,49.01,4.0,4.6,NCR,2024-04-28 08:11:58
74436,2024-07-02,00:00:00,CNR5235189316,Completed,CID262523,Bike,Hosur Road,Sarjapur Road,84.0,55.0,...,NaN,0,NaN,134.0,UPI,15.00,4.3,3.0,Bangalore,2024-07-02 00:00:00
232094,2024-06-26 00:00:00,20:18:38,CNR7578421,Cancelled by Driver,CID1714285,Auto,Dwarka Sector 21,Okhla,3.3,NaN,...,Over Capacity,0,NaN,NaN,Unknown,NaN,NaN,NaN,NCR,2024-06-26 20:18:38

In [104]:
# Hour (0–23)
combined_df["Hour"] = combined_df["DateTime"].dt.hour

# Day of month (1–31)
combined_df["Day"] = combined_df["DateTime"].dt.day

# Month (1–12)
combined_df["Month"] = combined_df["DateTime"].dt.month

# Weekday name (Monday, Tuesday…)
combined_df["Weekday"] = combined_df["DateTime"].dt.day_name()

In [105]:
combined_df[["DateTime", "Hour", "Day", "Month", "Weekday"]].head()

    DateTime  Hour  Day  Month   Weekday
0 2024-07-26     0   26      7    Friday
1 2024-07-25     0   25      7  Thursday
2 2024-07-30     0   30      7   Tuesday
3 2024-07-22     0   22      7    Monday
4 2024-07-02     0    2      7   Tuesday

In [106]:
combined_df["Is_Weekend"] = combined_df["Weekday"].isin(["Saturday", "Sunday"]).astype(int)

In [107]:
def get_time_slot(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

combined_df["Time_Slot"] = combined_df["Hour"].apply(get_time_slot)

In [108]:
combined_df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,...,Driver_Rating,Customer_Rating,City,DateTime,Hour,Day,Month,Weekday,Is_Weekend,Time_Slot
0,2024-07-26,00:00:00,CNR7153255142,Cancelled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,NaN,NaN,Bangalore,2024-07-26,0,26,7,Friday,0,Night
1,2024-07-25,00:00:00,CNR2940424040,Completed,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,4.1,4.0,Bangalore,2024-07-25,0,25,7,Thursday,0,Night
2,2024-07-30,00:00:00,CNR2982357879,Completed,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,4.2,4.8,Bangalore,2024-07-30,0,30,7,Tuesday,0,Night
3,2024-07-22,00:00:00,CNR2395710036,Cancelled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,NaN,NaN,Bangalore,2024-07-22,0,22,7,Monday,0,Night
4,2024-07-02,00:00:00,CNR1797421769,Completed,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,4.0,3.0,Bangalore,2024-07-02,0,2,7,Tuesday,0,Night

In [109]:
bangalore[["Date", "Time"]].head(10)

         Date      Time
0  2024-07-26  00:00:00
1  2024-07-25  00:00:00
2  2024-07-30  00:00:00
3  2024-07-22  00:00:00
4  2024-07-02  00:00:00
5  2024-07-13  00:00:00
6  2024-07-23  00:00:00
7  2024-07-11  00:00:00
8  2024-07-01  00:00:00
9  2024-07-18  00:00:00

In [110]:
import pandas as pd

bangalore = pd.read_csv("cleaned_bangalore.csv")
ncr = pd.read_csv("cleaned_ncr.csv")

In [111]:
bangalore["DateTime"] = pd.to_datetime(
    bangalore["Date"].astype(str) + " " + bangalore["Time"].astype(str),
    errors="coerce"
)

ncr["DateTime"] = pd.to_datetime(
    ncr["Date"].astype(str) + " " + ncr["Time"].astype(str),
    errors="coerce"
)

In [112]:
combined_df = pd.concat([bangalore, ncr], ignore_index=True)

In [113]:
combined_df.drop(columns=["Date", "Time"], inplace=True)

In [114]:
# Hour
combined_df["Hour"] = combined_df["DateTime"].dt.hour

# Day
combined_df["Day"] = combined_df["DateTime"].dt.day

# Month
combined_df["Month"] = combined_df["DateTime"].dt.month

# Weekday
combined_df["Weekday"] = combined_df["DateTime"].dt.day_name()

# Weekend flag
combined_df["Is_Weekend"] = combined_df["Weekday"].isin(["Saturday", "Sunday"]).astype(int)

In [115]:
def get_time_slot(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

combined_df["Time_Slot"] = combined_df["Hour"].apply(get_time_slot)

In [116]:
combined_df["DateTime"] = pd.to_datetime(combined_df["DateTime"], errors="coerce")

In [117]:
print(combined_df.shape)
print(combined_df["City"].value_counts())
print(combined_df["Hour"].unique()[:10])

(253024, 27)
City
NCR          150000
Bangalore    103024
Name: count, dtype: int64
[14 22 19  3  9  4 11  1 23 13]

In [118]:
combined_df.head()

,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,VTAT,CTAT,Cancelled_By_Customer,Cancelled_By_Driver,...,Driver_Rating,Customer_Rating,City,DateTime,Hour,Day,Month,Weekday,Is_Weekend,Time_Slot
0,CNR7153255142,Cancelled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,0,1,...,NaN,NaN,Bangalore,2024-07-26 14:00:00,14,26,7,Friday,0,Afternoon
1,CNR2940424040,Completed,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,0,0,...,4.1,4.0,Bangalore,2024-07-25 22:20:00,22,25,7,Thursday,0,Night
2,CNR2982357879,Completed,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,0,0,...,4.2,4.8,Bangalore,2024-07-30 19:59:00,19,30,7,Tuesday,0,Evening
3,CNR2395710036,Cancelled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,1,0,...,NaN,NaN,Bangalore,2024-07-22 03:15:00,3,22,7,Monday,0,Night
4,CNR1797421769,Completed,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,0,0,...,4.0,3.0,Bangalore,2024-07-02 09:02:00,9,2,7,Tuesday,0,Morning

In [119]:
combined_df.to_csv("final_rides_data.csv", index=False)

In [120]:
files.download("final_rides_data.csv")